"""Automated migration

Revision ID: 1c4befc7026c
Revises: 5dfc896b0515
Create Date: 2025-05-04 17:48:26.121934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4befc7026c'
down_revision: Union[str, None] = '5dfc896b0515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_knowledge_base_id', table_name='projects')
    op.drop_constraint('projects_knowledge_base_id_fkey', 'projects', type_='foreignkey')
    op.drop_column('projects', 'knowledge_base_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('knowledge_base_id', sa.UUID(), autoincrement=False, nullable=True, comment='References knowledge base assets'))
    op.create_foreign_key('projects_knowledge_base_id_fkey', 'projects', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_projects_knowledge_base_id', 'projects', ['knowledge_base_id'], unique=True)
    # ### end Alembic commands ###
