"""Add login attempts tracking table

Revision ID: 3ab16fc81c9e
Revises: 651a20616543
Create Date: 2025-03-22 05:42:02.750130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab16fc81c9e'
down_revision: Union[str, None] = '651a20616543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema with login attempts tracking table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=150), nullable=False),
        sa.Column('ip_address', sa.String(length=45), nullable=False),
        sa.Column('user_agent', sa.String(length=500), nullable=True),
        sa.Column('attempt_time', sa.TIMESTAMP(), nullable=False),
        sa.Column('success', sa.Boolean(), nullable=False, default=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_username'), 'login_attempts', ['username'], unique=False)
    op.create_index(op.f('ix_login_attempts_ip_address'), 'login_attempts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_login_attempts_attempt_time'), 'login_attempts', ['attempt_time'], unique=False)
    op.create_index(
        'ix_login_attempts_ip_attempt_time', 
        'login_attempts', 
        ['ip_address', 'attempt_time'], 
        unique=False
    )
    op.create_index(
        'ix_login_attempts_username_attempt_time', 
        'login_attempts', 
        ['username', 'attempt_time'], 
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema, removing login attempts tracking table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_login_attempts_username_attempt_time', table_name='login_attempts')
    op.drop_index('ix_login_attempts_ip_attempt_time', table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempt_time'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ip_address'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_username'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
